INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (1, 'Grado en Bellas Artes');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (1, 'Grado en Historia del Arte');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (2, 'Grado en Ingeniería Informática');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (2, 'Grado en Ingeniería del Software');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (3, 'Grado en Telecomunicaciones');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (3, 'Grado en Ingeniería Espacial');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (4, 'Grado en Derecho');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (4, 'Grado en Administración y Dirección de Empresas');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (5, 'Grado en Doctorado');
INSERT INTO `willyfog_db`.`degree` (centre_id, name) VALUES (5, 'Grado en Medicina');