INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (1, 'T3Rp', 1, 'Historia de España', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (2, 'B3Ht', 2, 'Arte Moderno', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (3, 'Q2RO', 3, 'Cálculo', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (4, 'jvdH', 4, 'Estructuras de Datos', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (5, 'SCVg', 5, 'Redes y Sistemas', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (6, 'ReyO', 6, 'Física I', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (7, 'xz6S', 7, 'Derecho Romano', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (8, 'G4TH', 8, 'Microeconomía', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (9, 'RvZz', 9, 'Investigación', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (10, 'fT4q', 10, 'Anatomía I', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (11, 'JZs8', 1, 'Dibujo Técnico', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (12, 'mkQH', 2, 'Historia de Grecia', 6);
INSERT INTO `willyfog_db`.`subject` (id, code, degree_id, name, credits) VALUES (13, '1Dvw', 3, 'Lógica Computacional', 6);